# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 10
    schedule:
        interval: "daily"
    assignees:
        - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "dependency"


  ######################################################################################################################
  #
  # Tools dependecy configuration - (ecs)
  #
  ######################################################################################################################

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/ecs"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 3
    schedule:
        interval: "daily"
    assignees:
        - "zerai"
    commit-message:
        include: "scope"
        prefix: "composer"
    labels:
        - "tool dependency"
