name: Commit stage

on: [ push, pull_request ]

env:

    PHP_EXTENSIONS: gd
    PHP_EXTENSIONS_CACHE_KEY: cache-php-extensions-v1

jobs:
    lint-composer:
        runs-on: ubuntu-18.04
        timeout-minutes: 5
        strategy:
            matrix:
                php:
                    - '8.1'
            fail-fast: true

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup php extension cache environment
              id: cache-php-extensions
              uses: shivammathur/cache-extensions@v1
              with:
                  php-version: ${{ matrix.php }}
                  extensions: ${{ env.PHP_EXTENSIONS }}
                  key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}

            - name: Cache PHP extensions
              uses: actions/cache@v2
              with:
                  path: ${{ steps.cache-php-extensions.outputs.dir }}
                  key: ${{ steps.cache-php-extensions.outputs.key }}
                  restore-keys: ${{ steps.cache-php-extensions.outputs.key }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: ${{ env.PHP_EXTENSIONS }}
                  ini-values: memory_limit=-1
                  coverage: none
                  tools: composer, composer-normalize:2.22.0

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-composer-

            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-progress  --no-scripts --ansi

            - name: Run composer validate
              run: composer validate --strict --ansi

            - name: Run composer normalize
              run: composer-normalize --dry-run --ansi



    phpunit:
      name: Code tests (PHP ${{ matrix.php }})
      runs-on: ubuntu-18.04
      timeout-minutes: 5
      strategy:
        matrix:
          php:
            - '8.1'
        fail-fast: true

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup php extension cache environment
          id: cache-php-extensions
          uses: shivammathur/cache-extensions@v1
          with:
            php-version: ${{ matrix.php }}
            extensions: ${{ env.PHP_EXTENSIONS }}
            key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}

        - name: Cache PHP extensions
          uses: actions/cache@v2
          with:
            path: ${{ steps.cache-php-extensions.outputs.dir }}
            key: ${{ steps.cache-php-extensions.outputs.key }}
            restore-keys: ${{ steps.cache-php-extensions.outputs.key }}

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: ${{ env.PHP_EXTENSIONS }}
            ini-values: date.timezone=Europe/Rome, memory_limit=-1
            coverage: xdebug

        - name: Get Composer Cache Directory
          id: composer-cache
          run: echo "::set-output name=dir::$(composer config cache-files-dir)"

        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
            restore-keys: ${{ runner.os }}-php${{ matrix.php }}-composer-

        - name: Install Composer dependencies
          run: composer install --prefer-dist --no-progress --no-scripts --ansi

        - name: Run tests
          run: ./vendor/bin/phpunit



    psalm:
      name: Psalm (PHP ${{ matrix.php }})
      runs-on: ubuntu-18.04
      timeout-minutes: 5
      strategy:
        matrix:
          php:
            - '8.1'
        fail-fast: true

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup php extension cache environment
          id: cache-php-extensions
          uses: shivammathur/cache-extensions@v1
          with:
            php-version: ${{ matrix.php }}
            extensions: ${{ env.PHP_EXTENSIONS }}
            key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}

        - name: Cache PHP extensions
          uses: actions/cache@v2
          with:
            path: ${{ steps.cache-php-extensions.outputs.dir }}
            key: ${{ steps.cache-php-extensions.outputs.key }}
            restore-keys: ${{ steps.cache-php-extensions.outputs.key }}

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: ${{ env.PHP_EXTENSIONS }}
            ini-values: date.timezone=Europe/Rome, memory_limit=-1
            coverage: xdebug

        - name: Get Composer Cache Directory
          id: composer-cache
          run: echo "::set-output name=dir::$(composer config cache-files-dir)"

        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
            restore-keys: ${{ runner.os }}-php${{ matrix.php }}-composer-

        - name: Install Composer dependencies
          run: composer install --prefer-dist --no-progress --no-scripts --ansi

        - name: Install Psalm
          run: composer bin psalm install

        - name: Run Psalm
          run: ./vendor/bin/psalm



    ecs:
      name: Ecs (PHP ${{ matrix.php }})
      runs-on: ubuntu-18.04
      timeout-minutes: 5
      strategy:
        matrix:
          php:
            - '8.1'
        fail-fast: true

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup php extension cache environment
          id: cache-php-extensions
          uses: shivammathur/cache-extensions@v1
          with:
            php-version: ${{ matrix.php }}
            extensions: ${{ env.PHP_EXTENSIONS }}
            key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}

        - name: Cache PHP extensions
          uses: actions/cache@v2
          with:
            path: ${{ steps.cache-php-extensions.outputs.dir }}
            key: ${{ steps.cache-php-extensions.outputs.key }}
            restore-keys: ${{ steps.cache-php-extensions.outputs.key }}

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: ${{ env.PHP_EXTENSIONS }}
            ini-values: date.timezone=Europe/Rome, memory_limit=-1
            coverage: xdebug

        - name: Get Composer Cache Directory
          id: composer-cache
          run: echo "::set-output name=dir::$(composer config cache-files-dir)"

        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
            restore-keys: ${{ runner.os }}-php${{ matrix.php }}-composer-

        - name: Install Composer dependencies
          run: composer install --prefer-dist --no-progress --no-scripts --ansi

        - name: Install Ecs
          run: composer bin ecs install

        - name: Run Ecs
          run: ./vendor/bin/ecs



    behat:
      name: Behat tests (PHP ${{ matrix.php }})
      runs-on: ubuntu-18.04
      timeout-minutes: 5
      strategy:
        matrix:
          php:
            - '8.1'
        fail-fast: true

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup php extension cache environment
          id: cache-php-extensions
          uses: shivammathur/cache-extensions@v1
          with:
            php-version: ${{ matrix.php }}
            extensions: ${{ env.PHP_EXTENSIONS }}
            key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}

        - name: Cache PHP extensions
          uses: actions/cache@v2
          with:
            path: ${{ steps.cache-php-extensions.outputs.dir }}
            key: ${{ steps.cache-php-extensions.outputs.key }}
            restore-keys: ${{ steps.cache-php-extensions.outputs.key }}

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: ${{ env.PHP_EXTENSIONS }}
            ini-values: date.timezone=Europe/Rome, memory_limit=-1
            coverage: xdebug

        - name: Get Composer Cache Directory
          id: composer-cache
          run: echo "::set-output name=dir::$(composer config cache-files-dir)"

        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
            restore-keys: ${{ runner.os }}-php${{ matrix.php }}-composer-

        - name: Install Composer dependencies
          run: composer install --prefer-dist --no-progress --no-scripts --ansi

        - name: Run tests
          run: ./vendor/bin/behat


